version: '3.2'


services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=12345678
    ports:
      - "3306:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.1
    command: start --hostname-strict=false --https-key-store-file=/etc/keycloak-keystore.jks
    depends_on:
      - mysql
    environment: # Está como admin pois o KC precisa criar as tabelas
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8443:8443"
    volumes:
      - type: bind
        source: "config/keycloak-keystore.jks"
        target: "/etc/keycloak-keystore.jks"

  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686" # Jaeger UI
      - "14268:14268" # Receive legacy OpenTracing traces, optional
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver, not yet used by Quarkus, optional
      - "14250:14250" # Receive from external otel-collector, optional

  elasticsearch:
    image: elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
    networks:
      - elk
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:7.17.10
    depends_on:
      - elasticsearch
    networks:
      - elk
    ports:
      - "12201:12201/udp"
      - "5000:5000"
      - "9600:9600"
    volumes:
      - type: bind
        source: "pipelines"
        target: "/usr/share/logstash/pipeline"

  kibana:
    image: kibana:7.17.10
    depends_on:
      - elasticsearch
    networks:
      - elk
    ports:
      - "5601:5601"

networks:
  elk:
    driver: bridge